spring.application.name=game-platform-backend
spring.data.mongodb.uri=mongodb://localhost:27017/mini_jeux_db
spring.data.mongodb.database=mini_jeux_db
spring.data.mongodb.auto-index-creation=true
# Configuration JWT
app.jwt.secret=9a4f2c8d3b7a1e5f2g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d
app.jwt.expiration-ms=86400000
# Configuration Sécurité© (Tentatives de connexion)
app.security.max-failed-attempts=5
app.security.lock-duration-minutes=30

logging.level.org.springframework.security=DEBUG